# Server properties
server:
  port: 8761

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Discovery Service - Local Instance

# Spring application properties
spring:
  application:
    name: infra-discovery
  profiles:
    active: dev

# Eureka server properties
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health

# Logging properties
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mariuszilinskas: INFO

