# Server configuration
server:
  port: 8761

# Application metadata
info:
  app:
    environment: ${spring.profiles.active}
    name: ${spring.application.name}
    description: Streamix Eureka Discovery Service

# Spring application and infrastructure configuration
spring:
  application:
    name: infra-discovery

# Eureka server configuration
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Actuator and observability configuration
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health

# Application logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mariuszilinskas: INFO

